version: "3.9"
services:
  prisma-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.prisma
    image: 666203386231.dkr.ecr.eu-north-1.amazonaws.com/uslugar-prisma-tasks:latest
    env_file:
      - ./backend/.env
    working_dir: /app
    # Pokreni migracije i zatim Prisma seed (ukljuƒçuje i seed dokumentacije preko npm skripte)
    command: ["sh","-lc","npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run seed:documentation"]
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uslugar_db
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
